### ISSUE TITLE
Sample code doesn't run: OpenCV Error: Assertion failed (ni > 0 && ni == ni1) in collectCalibrationData

### ISSUE THREAD

**Issue by alexblack** [abidrahmank/OpenCV2-Python-Tutorials#87]
Code from https://github.com/abidrahmank/OpenCV2-Python-Tutorials/blob/master/source/py_tutorials/py_calib3d/py_calibration/py_calibration.rst fails to run

```
import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('*.jpg')

for fname in images:
    print 'Filename: ', fname
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (7,6),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        #cv2.drawChessboardCorners(img, (7,6), corners2,ret)
        #cv2.imshow('img',img)
        #cv2.waitKey(500)

print 'Objects points: {0}, image points: {1}'.format(objpoints, imgpoints)
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1])#,None,None)

cv2.destroyAllWindows()
```

```
OpenCV Error: Assertion failed (ni > 0 && ni == ni1) in collectCalibrationData, file /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/calib3d/src/calibration.cpp, line 3193
Traceback (most recent call last):
  File "calib.py", line 39, in <module>
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1])#,None,None)
cv2.error: /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/calib3d/src/calibration.cpp:3193: error: (-215) ni > 0 && ni == ni1 in function collectCalibrationData
```

**Comment by mgmacias95** [comment]
Hi @alexblack 

I had the same issue and after a little research I found the problem in [stackoverflow](http://stackoverflow.com/questions/31249037/calibrating-webcam-using-python-and-opencv-error#36441746)

I resolved it changing the shape of  `objp`:

```
objp = objp.reshape(-1,1,3)
```

Also I had another problem: the number of corners found by `findChessboardCorners` can be less than 7*6 (pattern size) so I just kept number of corners found 3D points:

```
corners2 = cv2.cornerSubPix(image=gray, corners=corners, winSize=(11,11), zeroZone=(-1,-1),
                            criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001))
imgpoints.append(corners2)
objpoints.append(objp[0:corners2.shape[0]])
```
after that the code worked fine 😄

**Comment by rabiafyz** [comment]
Hi @mgmacias95 

I did not understand what you mean by doing reshape obj. 
Do you mean reshap it at the time of initailization?

**Comment by mgmacias95** [comment]
Hi @rabiafyz

Yes, just before the _for_ loop:

```
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
objp = objp.reshape(-1,1,3)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('*.jpg')

for fname in images:
    print 'Filename: ', fname
    .
    .
    .
```

**Comment by petered** [comment]
I had a similar problem (`error: (-215) ni >= 0 in function collectCalibrationData`).  For me it was that my `objp` points were `float64` instead of `float32`, which  was not exactly obvious from that message.

**Comment by ujwalaparupalli** [comment]
Hi @mgmacias95 , 
 I am also having the same problem. I tried the above suggested changes but I am still getting the same error. Here is the code:

import numpy as np
import cv2 as cv
import glob
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((5*7,3), np.float64)
objp[:,:2] = np.mgrid[0:7,0:5].T.reshape(-1,2)
objp = objp.reshape(-1,1,3)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('/home/..../chessboard/*.jpg')
#print(images)
for fname in images:
    #print(fname)
    img = cv.imread(fname)
    #print(img)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    #print(gray)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,5), None)
    #print(ret)
    #print(corners)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(image=gray, corners=corners, winSize=(11,11), zeroZone=(-1,-1),
                            criteria=(cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001))
        
        #imgpointsfinal = imgpoints.append(corners2)
        imgpoints.append(corners2)
        objpoints.append(objp[0:corners2.shape[0]])
        #print('Objects points: {0}, image points: {1}'.format(objpoints, imgpoints))
        ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
        # Draw and display the corners
        #cv.drawChessboardCorners(img, (7,5), corners2, ret)
        #imgS = cv.resize(img, (800,600))
        #cv.imshow('img', imgS)
        #cv.waitKey(0)
cv.destroyAllWindows()
``
The error is as follows:

` File "/home/..../camcalib.py", line 43, in <module>
    ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
error: OpenCV(3.4.1) /io/opencv/modules/calib3d/src/calibration.cpp:3133: error: (-215) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function collectCalibrationData`

It would be great if some one can help me.

Thank you.

**Comment by ujwalaparupalli** [comment]
Hi @mgmacias95 @petered @alexblack ,

I am also having the same problem. I tried the above suggested changes but still of no help and getting the same error. can someone please help me.

Thank you.

**Comment by SaberD** [comment]
I had the same problem. I used a different size checkered board image. Mine was size 6,9 and not 7,6.
I got this error when i did not change the dimension in some, but not all the necessary places.
Below is the code that worked for me, with the checkered board image saved as "test.png" in the same folder as the python file. [link 🏁  ](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.emgu.com%2Fwiki%2Fimages%2FOpenCV_Chessboard3.png&f=1) to the image i used

```Python
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
imgpoints = [] # 2d points in image plane.
objpoints = [] # 3d point in real world space

img = cv2.imread("test2.png")

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Find the chess board corners
ret, corners = cv2.findChessboardCorners(gray, (6,9),None)

# If found, add object points, image points (after refining them)
if ret == True:
    objpoints.append(objp)

    corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
    imgpoints.append(corners2)

# Draw and display the corners
cv2.drawChessboardCorners(img, (6,9), corners2,ret)
cv2.imshow('img',img)
cv2.waitKey(500)
```
